services:
  db:
    image: mongo
    restart: always
    network_mode: "host"
    profiles: [ "dev", "prod" ]
    volumes:
      - "dbdata:/data/db"
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: db

  db-dashboard:
    image: mongo-express
    restart: always
    network_mode: "host"
    profiles: [ "dev" ]
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://root:root@127.0.0.1:27017/
      ME_CONFIG_BASICAUTH: false

volumes:
  dbdata:
